deptrac:
  paths:
    - ../src
  exclude_files:
    - .*test.*
    - '#^__CG__.*\.php$#'
  layers:
    - name: Application
      collectors:
        - type: classLike
          value: .*HexagonalPlayground\\Application\\.*
    - name: Domain
      collectors:
        - type: classLike
          value: .*HexagonalPlayground\\Domain\\.*
    - name: Infrastructure
      collectors:
        - type: classLike
          value: .*HexagonalPlayground\\Infrastructure\\.*
  ruleset:
    Application:
      - Domain
    Domain: ~
    Infrastructure:
      - Application
      - Domain
