---
database:
  user:     '%env(MYSQL_USER)%'
  password: '%env(MYSQL_PASSWORD)%'
  name:     '%env(MYSQL_DATABASE)%'
  host:     '%env(MYSQL_HOST)%'
  port:     '3306'

tables:
  pitches:
    converters:
      contact_first_name:
        converter: 'randomizeText'
      contact_last_name:
        converter: 'randomizeText'
      contact_phone:
        converter: 'randomizeNumber'
      contact_email:
        converter: 'randomizeEmail'
  public_key_credentials:
    truncate: true
  teams:
    converters:
      contact_first_name:
        converter: 'randomizeText'
      contact_last_name:
        converter: 'randomizeText'
      contact_phone:
        converter: 'randomizeNumber'
      contact_email:
        converter: 'randomizeEmail'
  users:
    truncate: true
  users_teams_link:
    truncate: true
