<?php
/**
 * HTML Email Template for inviting users (generated by GitHub Copilot)
 *
 * @var string $sender
 * @var string $receiver
 * @var DateTimeInterface $validUntil
 * @var string $targetLink
 */
?>
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Deine Einladung</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
    }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    img {
      display: block;
      max-width: 100%;
      height: auto;
    }
    .container {
      width: 100%;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      text-align: center;
      padding: 40px 0;
    }
    .content {
      background-color: #ffffff;
      padding: 20px;
      text-align: center;
    }
    .cta-button {
      background-color: #28a745;
      color: #ffffff;
      padding: 15px 25px;
      text-decoration: none;
      font-weight: bold;
      border-radius: 5px;
      display: inline-block;
      margin-top: 20px;
    }
    .footer {
      text-align: center;
      padding: 20px;
      font-size: 12px;
      color: #888888;
    }
  </style>
</head>
<body>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td align="center">
        <div class="container">
          <!-- Header -->
          <div class="header">
            <img src="https://www.wildeligabremen.de/wp-content/uploads/2023/05/cropped-Logo-mit-Schrift_30-Jahre-Kopie_2-e1683381765583.jpg" alt="Wilde Liga Bremen">
          </div>
          <!-- Content -->
          <div class="content">
            <h1>Deine Einladung</h1>
            <p>Hey <?php echo htmlentities($receiver); ?>, du wurdest von <?php echo htmlentities($sender); ?> zum Liga-Manager eingeladen.</p>
            <a href="<?php echo $targetLink; ?>" class="cta-button">Registrieren</a>
          </div>
          <!-- Footer -->
          <div class="footer">
            <p>Deine Einladung ist g&uuml;ltig bis: <?php echo $validUntil->format('d.m.Y H:i'); ?> Uhr.</p>
            <p>Bitte leite deine Einladung nicht an eine andere Person weiter.</p>
          </div>
        </div>
      </td>
    </tr>
  </table>
</body>
</html>