<?php
/**
 * HTML Email Template for inviting users (generated by GitHub Copilot)
 *
 * @var string $sender
 * @var string $receiver
 * @var DateTimeInterface $validUntil
 * @var string $targetLink
 */
?>
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Deine Einladung</title>
  <style>
    <?php echo file_get_contents(__DIR__ . '/assets/style.css'); ?>
  </style>
</head>
<body>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td align="center">
        <div class="container">
          <!-- Header -->
          <div class="header">
            <img src="data:image/jpeg;base64,<?php echo base64_encode(file_get_contents(__DIR__ . '/assets/logo.jpg')); ?>" alt="Wilde Liga Bremen">
          </div>
          <!-- Content -->
          <div class="content">
            <h1>Deine Einladung</h1>
            <p>Hey <?php echo htmlentities($receiver); ?>, du wurdest von <?php echo htmlentities($sender); ?> zum Liga-Manager eingeladen.</p>
            <a href="<?php echo $targetLink; ?>" class="cta-button">Registrieren</a>
          </div>
          <!-- Footer -->
          <div class="footer">
            <p>Deine Einladung ist g&uuml;ltig bis: <?php echo $validUntil->format('d.m.Y H:i'); ?> Uhr.</p>
            <p>Bitte leite deine Einladung nicht an eine andere Person weiter.</p>
          </div>
        </div>
      </td>
    </tr>
  </table>
</body>
</html>