version: '3'
server:
  command: "lima-worker"
  user: "www-data"
  group: "www-data"
http:
  address: "0.0.0.0:8080"
  pool:
    num_workers: 1
  middleware: [ "http_metrics" ]
metrics:
  address: "0.0.0.0:8081"
rpc:
  listen: tcp://127.0.0.1:6001
logs:
  channels:
    http:
      mode: raw
      level: panic
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: raw
      level: info
      encoding: console
      output: stdout
      err_output: stderr
    metrics:
      mode: raw
      level: info
      encoding: console
      output: stdout
      err_output: stderr
    rpc:
      mode: raw
      level: info
      encoding: console
      output: stdout
      err_output: stderr
