name: Build for PHP-FPM
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: make build
        env:
          TARGET_TYPE: "fpm"
      - name: Test
        run: make test
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Publish
        run: make publish
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
