name: Build for Roadrunner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build, Test & Publish
        run: bash build.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          PUBLISH_IMAGE: 1
          TARGET_TYPE: "roadrunner"
