name: Build for Roadrunner
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: make build
        env:
          TARGET_TYPE: "roadrunner"
      - name: Test
        run: make test
        env:
          COVERALLS_RUN_LOCALLY: 1
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "roadrunner"
      - name: Publish
        run: make publish
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "roadrunner"
