name: Build for PHP-FPM
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_RUNTIME: "fpm"
      APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: make build
      - name: Test with MariaDB
        run: make test
        env:
          DB_DRIVER: "pdo-mysql"
          DB_HOST: "mariadb"
      - name: Cleanup after MariaDB tests
        run: make clean
        if: always()
        env:
          DB_DRIVER: "pdo-mysql"
          DB_HOST: "mariadb"
      - name: Test with PostgreSQL
        run: make test
        env:
          DB_DRIVER: "pdo-pgsql"
          DB_HOST: "postgres"
      - name: Cleanup after PostgreSQL tests
        run: make clean
        if: always()
        env:
          DB_DRIVER: "pdo-pgsql"
          DB_HOST: "postgres"
      - name: Publish
        run: make publish
        if: github.ref_type == 'tag' || github.ref_name == 'master'
      - name: Cleanup
        run: make clean
        if: always()