name: Build for PHP-FPM
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build
        run: make build
        env:
          TARGET_TYPE: "fpm"
      - name: Test with MariaDB
        run: make test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          DB_DRIVER: "pdo-mysql"
          DB_HOST: "mariadb"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Cleanup after MariaDB tests
        run: make clean
        if: always()
        env:
          DB_DRIVER: "pdo-mysql"
          DB_HOST: "mariadb"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Test with PostgreSQL
        run: make test
        env:
          DB_DRIVER: "pdo-pgsql"
          DB_HOST: "postgres"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Cleanup after PostgreSQL tests
        run: make clean
        if: always()
        env:
          DB_DRIVER: "pdo-pgsql"
          DB_HOST: "postgres"
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Publish
        run: make publish
        if: github.ref_type == 'tag' || github.ref_name == 'master'
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"
      - name: Cleanup
        run: make clean
        if: always()
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TARGET_TYPE: "fpm"